name: Run autp_anki_card_creation.py Script and Commit Changes

on:
  push:
    branches:
      - main  # Monitoring main branch
      - develop # Monitoring develop branch
    paths:
      - 'src/content/terms/**'  # Monitoring folder

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Autentication to Actions to commit

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: |
        python src/scripts/auto_anki_card_creation.py

    - name: Check for changes
      run: |
        git status
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected, committing..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Add files generated by auto_anki_card_creation.py. Check src/content/anki_deck."
          git push origin main
        else
          echo "No changes to commit"
        fi
